export const journalRegistryAbi = [
  {
    type: "function",
    name: "journalName",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "activeReviewerCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "activeSubmissionCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "completedReviewCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "genesisCouncilActive",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export const submissionRegistryAbi = [
  {
    type: "function",
    name: "createSubmission",
    stateMutability: "nonpayable",
    inputs: [
      { name: "title", type: "string" },
      { name: "abstractText", type: "string" },
      { name: "manifestURI", type: "string" },
      { name: "contentURI", type: "string" },
      { name: "mirrorURI", type: "string" },
      { name: "licenseCode", type: "string" },
      { name: "authorRefs", type: "string[]" },
      { name: "dataURIs", type: "string[]" },
      { name: "codeURIs", type: "string[]" },
    ],
    outputs: [{ name: "submissionId", type: "uint256" }],
  },
  {
    type: "function",
    name: "submissionCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getSubmission",
    stateMutability: "view",
    inputs: [{ name: "submissionId", type: "uint256" }],
    outputs: [
      {
        components: [
          { name: "id", type: "uint256" },
          { name: "author", type: "address" },
          { name: "latestVersionId", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "createdAt", type: "uint256" },
          { name: "updatedAt", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "function",
    name: "getVersion",
    stateMutability: "view",
    inputs: [
      { name: "submissionId", type: "uint256" },
      { name: "versionId", type: "uint256" },
    ],
    outputs: [
      {
        components: [
          { name: "versionId", type: "uint256" },
          { name: "parentVersionId", type: "uint256" },
          { name: "title", type: "string" },
          { name: "abstractText", type: "string" },
          { name: "manifestURI", type: "string" },
          { name: "contentURI", type: "string" },
          { name: "mirrorURI", type: "string" },
          { name: "licenseCode", type: "string" },
          { name: "authorRefs", type: "string[]" },
          { name: "dataURIs", type: "string[]" },
          { name: "codeURIs", type: "string[]" },
          { name: "createdAt", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "function",
    name: "addVersion",
    stateMutability: "nonpayable",
    inputs: [
      { name: "submissionId", type: "uint256" },
      { name: "parentVersionId", type: "uint256" },
      { name: "title", type: "string" },
      { name: "abstractText", type: "string" },
      { name: "manifestURI", type: "string" },
      { name: "contentURI", type: "string" },
      { name: "mirrorURI", type: "string" },
      { name: "dataURIs", type: "string[]" },
      { name: "codeURIs", type: "string[]" },
    ],
    outputs: [{ name: "versionId", type: "uint256" }],
  },
] as const;

export const reviewRegistryAbi = [
  {
    type: "function",
    name: "reviewCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "disputeCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getReview",
    stateMutability: "view",
    inputs: [{ name: "reviewId", type: "uint256" }],
    outputs: [
      {
        components: [
          { name: "id", type: "uint256" },
          { name: "submissionId", type: "uint256" },
          { name: "reviewer", type: "address" },
          { name: "isSelfNominated", type: "bool" },
          { name: "conflictStatement", type: "string" },
          { name: "openedAt", type: "uint256" },
          { name: "dueAt", type: "uint256" },
          { name: "submitted", type: "bool" },
          { name: "methodologyScore", type: "uint8" },
          { name: "noveltyScore", type: "uint8" },
          { name: "rigorScore", type: "uint8" },
          { name: "clarityScore", type: "uint8" },
          { name: "recommendation", type: "uint8" },
          { name: "summary", type: "string" },
          { name: "reviewURI", type: "string" },
          { name: "submittedAt", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "function",
    name: "getDispute",
    stateMutability: "view",
    inputs: [{ name: "disputeId", type: "uint256" }],
    outputs: [
      {
        components: [
          { name: "id", type: "uint256" },
          { name: "targetType", type: "uint8" },
          { name: "targetId", type: "uint256" },
          { name: "opener", type: "address" },
          { name: "reason", type: "string" },
          { name: "evidenceURI", type: "string" },
          { name: "resolved", type: "bool" },
          { name: "upheld", type: "bool" },
          { name: "resolutionURI", type: "string" },
        ],
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "function",
    name: "openReview",
    stateMutability: "nonpayable",
    inputs: [
      { name: "submissionId", type: "uint256" },
      { name: "reviewer", type: "address" },
      { name: "isSelfNominated", type: "bool" },
      { name: "conflictStatement", type: "string" },
      { name: "dueAt", type: "uint256" },
    ],
    outputs: [{ name: "reviewId", type: "uint256" }],
  },
  {
    type: "function",
    name: "submitReview",
    stateMutability: "nonpayable",
    inputs: [
      { name: "reviewId", type: "uint256" },
      { name: "methodologyScore", type: "uint8" },
      { name: "noveltyScore", type: "uint8" },
      { name: "rigorScore", type: "uint8" },
      { name: "clarityScore", type: "uint8" },
      { name: "recommendation", type: "uint8" },
      { name: "summary", type: "string" },
      { name: "reviewURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "openDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "targetType", type: "uint8" },
      { name: "targetId", type: "uint256" },
      { name: "reason", type: "string" },
      { name: "evidenceURI", type: "string" },
    ],
    outputs: [{ name: "disputeId", type: "uint256" }],
  },
  {
    type: "event",
    name: "DecisionRecorded",
    anonymous: false,
    inputs: [
      { name: "submissionId", type: "uint256", indexed: true },
      { name: "decision", type: "uint8", indexed: true },
      { name: "rationaleURI", type: "string", indexed: false },
    ],
  },
] as const;

export const reputationSbtAbi = [
  {
    type: "function",
    name: "getProfile",
    stateMutability: "view",
    inputs: [{ name: "subject", type: "address" }],
    outputs: [
      {
        components: [
          { name: "totalPoints", type: "uint256" },
          { name: "reviewerWeight", type: "uint256" },
          { name: "authorWeight", type: "uint256" },
          { name: "editorWeight", type: "uint256" },
          { name: "metadataURI", type: "string" },
        ],
        name: "",
        type: "tuple",
      },
    ],
  },
  {
    type: "event",
    name: "ReputationGranted",
    anonymous: false,
    inputs: [
      { name: "subject", type: "address", indexed: true },
      { name: "role", type: "uint8", indexed: true },
      { name: "points", type: "uint256", indexed: false },
      { name: "totalPoints", type: "uint256", indexed: false },
      { name: "reason", type: "string", indexed: false },
      { name: "metadataURI", type: "string", indexed: false },
    ],
  },
] as const;
